---
- hosts: proxmoxcontainer
  become: yes
  become_user: root
  serial: 1
  tasks:
  - shell: "(sleep 2 && shutdown -r now) &"
  - wait_for_connection: 30 
  - local_action: shell ansible -u {{ ansible_user_id }} -m ping {{ inventory_hostname }}
      register: result
      until: result.rc == 0
      retries: 30
      delay: 10
    - shell: uptime
